### ISSUE TITLE
different than string.underscore

### ISSUE THREAD

**Issue by UziTech** [blakeembrey/snake-case#4]
I ran into an issue when comparing this with [string.underscore](https://www.npmjs.com/package/string#--underscore)

specifically when multiple capital letter are in a camel case string.

```javascript
string("thisIDForThatThing").underscore().s
// "this_id_for_that_thing"

snakeCase("thisIDForThatThing")
// "this_idfor_that_thing"
```

**Comment by blakeembrey** [comment]
To be honest, these are different libraries so they'll always be different. This seems like a reasonable thing to correct though (the fix should occur in https://github.com/blakeembrey/sentence-case and the fix is to match `([\\p{Lu}\\p{N}]+)(\\p{Ll})` to split.

Another case that's different between them are number handling. E.g. `test2012`.
